---
title: "`r emo::ji('Japan')` Project-wide Code of Conduct statement for Bioconductor (Japanese, Japan)"
---

([BioC 2020 の行動規範] から改作[1]、 [英語](en-US.html) から翻訳)

# 行動規範

## バージョン 1.2.0 (2022年11月25日)

_初のプロジェクト全体の行動規範、以前のカンファレンス特有のドキュメントを拡大_

Bioconductorコミュニティは以下を重視します：

* アイデア、コード、ソフトウェア、専門知識の共有
* 協力
* 多様性と包括性
* 優しく歓迎する環境
* コミュニティへの貢献

これらの価値観を共有するBioconductorは、次の要素に関わらず、ハラスメント、脅迫、いじめのない、歓迎される支援的で友好的な体験を提供することを専念しています：

* アイデンティティ：性別、性自認と表現、性的指向、障害、身体的外見、民族性、体型、人種、年齢、宗教、言語、など
* 知的立場：データ分析のアプローチ、ソフトウェアの嗜好、コーディングスタイル、科学的視点、キャリア段階、など

このコミュニティに参加することで、あなたはBioconductorが後援するイベント（対面または仮想のもの、例えば講演、ワークショップ、ポスターセッション、社交活動等）や、電子通信チャンネル（例えばコミュニティ-bioc [Slack](https://slack.bioconductor.org/)、サポートサイト、オンラインフォーラム、パッケージレビューサイト、ソーシャルメディア通信等）、またはパッケージ（コミットを含む）で、これらの価値観に反する行動をとらないことに同意していただきます。さらに、Bioconductorのオンラインフォーラムの全ての参加者には、識別可能なアカウントを持つことを求めています。要求に従って匿名性を放棄しないアカウントは削除される可能性があります。

私たちは、コミュニティメンバーへのハラスメント、脅迫、いじめを容認しません。性的な言葉遣いやイメージは、プレゼンテーション、コミュニケーション、またはオンライン会場、チャットなどで適切ではありません。

行動規範を違反した人は、行動規範委員会の裁量により、一時的または永久的に電子プラットフォームまたはイベントから制裁を受けたり、追放されることがあります。

#### _許されないハラスメント、脅迫、いじめの行為の例_

ハラスメントには、以下が含まれますが、これらに限定されません：

* 他人を小さく見せる、または軽蔑するコメントをチャット、視聴者、または個人的に行う
* オンラインで性的な画像を共有する
* ハラスメント的な写真撮影や録音
* 講演や他のイベントの持続的な妨害
* 望まない性的な注意
* 上記の行為を推奨する、または奨励する

脅迫といじめには、以下が含まれますが、これらに限定されません：

* 攻撃的または威嚇的な行動
* 他人の知性、仕事、視点、または質問/コメントを嘲笑または侮辱する
* 科学的な議論の文脈で、性別、性自認と表現、性的指向、障害、身体的外見、体型、人種、年齢、宗教、または他の個人的属性を参照する
* 故意に誰かを不歓迎な気分にさせる
* トローリング行為（故意に煽る、または攻撃的なメッセージ）
* 持続的なオフトピックの投稿

## 執行
ハラスメントや脅迫的な行動を止めるよう求められた者は、直ちに従うことが求められます。

行動規範に違反した人に対しては、行動規範委員会はすべてのコミュニティメンバーにとって歓迎的な環境を確保するために必要な行動をとる権利を保有します。これには、疑われる違反者に警告を発したり、Bioconductorの管理下にあるイベントや電子プラットフォームから一時的/永久的に追放することも含まれます。

行動規範委員会は、イベントや電子通信プラットフォームの妨害、または任意のコミュ

ニティメンバーに対する環境の敵対的な作成を意図した、またはその明確な影響のある何かを修正する行動をとることがあります。

Bioconductorコミュニティの全ての人々に、Bioconductorのイベントとオンライン通信プラットフォームでの参加時に、行動規範を遵守することを期待しています。

## 報告
もし誰かがあなた自身、または他の人を不安にさせたり、歓迎されない気分にさせるような行動をとった場合は、できるだけ早く報告してください。報告は匿名でも、または個人名で行うことができます。すべての報告は行動規範委員会によって審査され、秘密に保たれます。

#### _電子的に_

次のリンクから匿名または非匿名で報告をすることができます：https://forms.gle/gEWHBWnXvZbEdFsq5. これは行動規範委員会に転送される自由形式のテキストボックスです。代わりに行動規範委員会（code-of-conduct@bioconductor.org）にメールを送ることもできます。グループとして行動規範委員会に報告することに不安がある場合は、電子メールまたはコミュニティ-bioc Slackチャンネルのダイレクトメッセージで個々の委員会メンバーに連絡することができます。可能な限り関連する全ての電子会話のスクリーンショット/コピーを含めてください（あなたの匿名性を損なう必要はありません！）。

私たちはあなたの匿名の報告に直接フォローアップすることはできませんが、完全に調査し、再発防止のために必要な行動をとることができます。

#### _個人報告（Bioconductorの全てのイベント：対面または仮想）_

イベントに出席している行動規範委員会のメンバーに個人的に報告をすることができます。

個人的な報告を受け取る際、私たちはあなたが安全で、他人に聞かれることがないことを確認します。他のイベントスタッフを巻き込むことで、あなたの報告が適切に管理されることを確認します。安全になったら、何が起こったのかを私たちに話していただきます。これは落ち込むこともあるかもしれませんが、私たちはできるだけ敬意を持って扱います。あなたはサポートのために誰かを連れてくることができます。あなたは誰かと対峙するよう求められることはありませんし、私たちは誰にもあなたが誰であるかを告げることはありません。

私たちのチームは、あなたが必要とする支援（例えばホテル/会場のセキュリティへの連絡、地元の法執行機関、地元の支援サービス、エスコートの提供、あるいはイベントの期間中に安全を感じるためのその他の支援）を得るために喜んで助けます。

私たちはあなたのBioconductorイベントへの出席と参加を重視しています。

#### _オンブズパーソン_

Bioconductorと関係のない人物があなたの紛争解決を監督することを望むことを理解しています。これを実現するため、行動規範委員会はBioconductorプロジェクト

のメンバーとは異なるオープンソースコミュニティからオンブズパーソンを任命します。彼らは行動規範委員会が下す、変更する、または棄却する決定の権限はありませんが、コンサルテーション、仲裁、コーチング、その他のリソースへの紹介を提供することでコミュニティメンバーを支援することができます。オンブズパーソンは、機密性、公平性、非公式性、独立性を保証するために、直接電子メール（以下参照）で連絡を取ることができます。

#### _インシデント手順_

行動規範委員会は、紛争を処理するための標準的な手順を採用しています。この手順は、[ここ](https://bioconductor.github.io/CodeOfConduct/incident_response.html)で簡単にまとめられています。インシデント手順はValerie AuroraとMary Gardinerによる本 "How to Respond to Code of Conduct Reports" に基づいています。

### 行動規範委員会

* (議長) Saskia Freytag <sas.freytag@gmail.com> (until 2023)
* Yagoub Adam <yagoub@alumni.usp.br> (until 2022)
* Leonardo Collado-Torres <lcolladotor@gmail.com> (until 2022)
* Laurent Gatto <laurent.gatto@gmail.com> (until 2023)
* Michael Love <michaelisaiahlove@gmail.com> (until 2024)
* Federico Marini <fede.maro@gmail.com> (until 2024)
* Sowmya Parthiban <sowmyaparthiban@gmail.com> (until 2024)
* Anna Quaglieri <anna.quaglieri16@gmail.com> (until 2024)
* Johannes Rainer <johannes.rainer@eurac.edu> (until 2023)
* Lluís Revilla <lluis.revilla@gmail.com> (until 2024)
* Charlotte Soneson <charlottesoneson@gmail.com> (until 2023)

[1]: https://bioc2020.bioconductor.org/code_of_conduct
